sonar.projectKey=FleetOps-Maintenance-Service
sonar.projectName=FleetOps-Maintenance-Service
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/target/**,**/build/**,**/dist/**,**/coverage/**
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*
